Friend Module MenuItems
    Friend Const Categories As String = "Categories..."
    Friend Const CategoryReport = "Category Report"
    Friend Const ChangeAbbreviation As String = "Change Abbreviation..."
    Friend Const ChangeName As String = "Change Name..."
    Friend Const CollectionReport = "CollectionReport"
    Friend Const Collections = "Collections..."
    Friend Const DeleteCategory As String = "Delete Category"
    Friend Const DeleteCollection = "Delete Collection"
    Friend Const GoBack As String = "Go Back"
    Friend Const MediaTypes = "Media Types..."
    Friend Const NewCategory As String = "New Category..."
    Friend Const NewCollection = "New Collection..."
    Friend Const NewMediaType = "New Media Type..."
    Friend Const Ok As String = "Ok"
    Friend Const Quit As String = "Quit"
End Module
